name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Checkout Submodules
        shell: bash
        run: |
          git submodule sync
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1
      - name: Clippy
        run: cargo clippy --verbose --all
      - name: Build
        run: cargo build --verbose --all
      - name: Run tests
        run:
          cargo test --verbose --all
      - name: Check benchmarks
        run: cargo clippy --benches